root: true
parser: "@typescript-eslint/parser"
env:
  node: true
  es6: true
ignorePatterns:
  - out
  - node_modules
  - .vscode-test
  - .yarn
  - "**/*.d.ts"
parserOptions:
  ecmaVersion: 6
  sourceType: module
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
