ignoreWorkspaceRootCheck: true
saveExact: true
shamefullyHoist: true
shellEmulator: true

overrides:
  jiti: <2.5.0
  form-data: 4.0.4
  on-headers: 1.1.0
  koa: 2.16.2
  tmp: 0.2.5

onlyBuiltDependencies:
  - esbuild
  - eslint-plugin-node-dependencies
