autoInstallPeers: false

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - eslint-plugin-node-dependencies

overrides:
  form-data: 4.0.4
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  koa@>=2.16.2 <2.16.3: '>=2.16.3'
  on-headers: 1.1.0
  tar-fs@>=3.0.0 <3.1.1: '>=3.1.1'
  tmp: 0.2.5
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'

saveExact: true

shamefullyHoist: true

shellEmulator: true
