name: CI

on:
  push:
    branches: [main, "renovate/**"]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 18.17.0 # renovate: datasource=node depName=node

      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_NM_MODE: "hardlinks-local"

      - name: Check formatting
        run: yarn check-format

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test
