name: CI

on:
  push:
    branches: [main, "renovate/**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 18.12.1 # renovate: datasource=node depName=node

      - name: Configure
        shell: bash
        run: |
          npm config set scripts-prepend-node-path true
          echo "Node $(node --version)"
          echo "Yarn $(yarn --version)"

      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Get Yarn cache
        id: yarn-config
        run: |
          echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
          echo "INSTALL_STATE_PATH=$(yarn config get installStatePath)" >> $GITHUB_OUTPUT

      - name: Restore Yarn cache
        uses: actions/cache@c17f4bf4666a8001b1a45c09eb7a485c41aa64c3 # v3.2.0
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          path: ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
          restore-keys: |
            yarn-cache-

      - name: Restore Yarn install state
        id: yarn-install-state-cache
        uses: actions/cache@c17f4bf4666a8001b1a45c09eb7a485c41aa64c3 # v3.2.0
        with:
          key: ${{ runner.os }}-yarn-install-state-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
          path: ${{ steps.yarn-config.outputs.INSTALL_STATE_PATH }}

      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_NM_MODE: "hardlinks-local"

      - name: Check formatting
        run: yarn check-format

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test
