name: CI

on:
  push:
    branches: [main, "renovate/**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 18.12.1 # renovate: datasource=node depName=node

      - name: Configure
        shell: bash
        run: |
          npm config set scripts-prepend-node-path true
          echo "Node $(node --version)"
          echo "Yarn $(yarn --version)"

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Get Yarn cache
        id: yarn-config
        run: |
          echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
          echo "INSTALL_STATE_PATH=$(yarn config get installStatePath)" >> $GITHUB_OUTPUT

      - name: Restore Yarn cache
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          path: ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
          restore-keys: |
            yarn-cache-

      - name: Restore Yarn install state
        id: yarn-install-state-cache
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        with:
          key: ${{ runner.os }}-yarn-install-state-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
          path: ${{ steps.yarn-config.outputs.INSTALL_STATE_PATH }}

      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_NM_MODE: "hardlinks-local"

      - name: Check formatting
        run: yarn check-format

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test
