name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, ready_for_review, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-$${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: pnpm
          node-version-file: .node-version

      - name: Install dependencies
        run: pnpm bootstrap

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Run web tests
        run: pnpm test:web

      - name: Build
        run: pnpm build
